Draft Posts
greenpress/admin-panel pull request #49
Opened 2020-10-13 13:47 UTC by itays123

**NOTE: this is not complete, just wanted your reviews before moving forward**

2020-10-13 13:51 UTC, itays123 commented
It seems like the build is failing because of missing types in the vue composition api

2020-10-13 14:06 UTC, davidmeirlevy commented on src/services/drafts.ts
> +export function getDraft(contextType: string, contextId: string|null): Promise<any> {
use the crud service...
see other services for reference.

2020-10-13 15:46 UTC, itays123 commented on src/services/drafts.ts
> +export function getDraft(contextType: string, contextId: string|null): Promise<any> {
The routes aren't exactly the same...

2020-10-13 16:07 UTC, davidmeirlevy commented on src/modules/posts/compositions/draft-post.ts
> +  }
You make a hook for drafts, so it's obvious those are drafts methods, so just return them as:
{ save, remove, draft }

2020-10-13 16:12 UTC, davidmeirlevy commented on src/services/drafts.ts
> +  return api.put('/api/drafts', { data: draftData });
you don't chain the "getCallData" like in `getDraft`. that's why your build failed.

2020-10-13 16:20 UTC, itays123 commented
still failing. I'll look into it

2020-10-13 16:29 UTC, davidmeirlevy commented
build locally before commit to see the errors:
https://g.codefresh.io/build/5f85d373f71e7398cd8f55fb?step=5f85d373f71e7398cd8f55fb&tab=output&logs=terminal

lint errors.

2020-10-13 16:57 UTC, itays123 commented
> lint errors.

CodeFresh doesn't let me view the console. what do I need to fix?

2020-10-13 17:57 UTC, davidmeirlevy commented
run it locally, you'll get the lint errors in the terminal.

2020-10-13 18:30 UTC, itays123 commented
Build is successful!
Note that I deleted my entire custom hook and just worked on the existing hooks so all functionality is supposed to work. now the "debounce" feature is the only thing left to do.

2020-10-13 19:01 UTC, davidmeirlevy requested changes

2020-10-14 05:18 UTC, itays123 commented on src/services/drafts.ts
> +export function getDraft(contextType: string, contextId: string|null): Promise<any> {
where is that folder?

2020-10-14 05:37 UTC, davidmeirlevy reviewed
I mentioned a tiny improvement.

Also, can you test the whole flow to see if it works? (Admin, front proxy, cli config, drafts service..)

2020-10-14 05:37 UTC, davidmeirlevy commented on src/modules/posts/compositions/unsaved-changes.ts
> +export function useUnsavedChanges(postId: string|null = null, editedPost: any) {
The editedPost should be a Ref<any>, or else the watchEffect will not work..

2020-10-14 05:46 UTC, itays123 commented
> I mentioned a tiny improvement.
> 
> Also, can you test the whole flow to see if it works? (Admin, front proxy, cli config, drafts service..)

I'm having some trouble setting up a full greenpress environment. After I'll finish the denounce feature and the front proxy I'll try

2020-10-14 08:19 UTC, davidmeirlevy commented
There's a lodash-debounce in this project. You can use it and see a reference on how to use it.

2020-10-14 09:26 UTC, davidmeirlevy requested changes

2020-10-14 09:26 UTC, davidmeirlevy commented on src/modules/posts/compositions/unsaved-changes.ts
> +    debounce(() => {
that's not how to use debounce.
you need to wrap savePostDraft with `debounce`, and use the debounced-function.

2020-10-14 10:52 UTC, davidmeirlevy approved these changes

2020-10-14 15:11 UTC, merged