first implementation of gcs auth secrets component
greenpress/admin-panel pull request #58
Opened 2020-12-06 20:32 UTC by drorrose

2020-12-07 09:14 UTC, davidmeirlevy requested changes
look at `src/modules/assets/components/StorageForm.vue:26` - the type there should be fixed to `gcs`.
also, your indentation is not like the rest of the project. you can run i think `npm run lint` should help you fix it locally.

2020-12-07 09:14 UTC, davidmeirlevy commented on src/modules/assets/components/StorageGcsAuth.vue
> +    <FormInput title="Username" v-model="form.username" />
I won't go for this approach.
The users have a JSON file from google.
1. use a `<input type="file"/>` to select the file from there computer (instead of entering the data from it)
2. read the file at the client-side (it's a JSON, not hard to read it).
3. you can emit this JSON object to the parent component (file storage form) - it should include all those values anyway.
4. maybe the bucket name should be a separated input. i think it's not located at the authentication file from google.

2020-12-07 09:14 UTC, davidmeirlevy commented on src/modules/assets/components/StorageForm.vue
> +		  v-if="editedStorage.kind === 'gcs'"
use `v-else-if`

2020-12-11 17:23 UTC, drorrose reviewed
Cool, was a learning experience :)

2020-12-14 14:06 UTC, davidmeirlevy commented on src/modules/assets/components/StorageForm.vue
> +		  v-if="editedStorage.kind === 'gcs'"
@drorrose I see I also forgot about it.

2020-12-27 10:48 UTC, davidmeirlevy approved these changes

2020-12-27 11:22 UTC, merged