Issue 59 i18n
greenpress/admin-panel pull request #60
Opened 2021-01-02 09:50 UTC by or-yam

I added some more hebrew translations for most of the admin panel. It still needs some improvements especially on the forms inputs.

2021-01-08 14:58 UTC, davidmeirlevy requested changes

2021-01-08 14:58 UTC, davidmeirlevy commented on src/modules/assets/components/StorageForm.vue
> +      :title="$t('Name')"
The right way is to use the translate function from inside the FormInput component, so it will be generic.

2021-01-08 14:58 UTC, davidmeirlevy commented on src/modules/core/components/layout/Header.vue
> +		<span class="user-welcome" v-if="user">{{$t('Hello')}} <strong>{{user.name}}</strong></span>
We should use variables inside the translated text, instead of translating single words inside a sentence.

2021-01-09 19:25 UTC, or-yam commented on src/modules/assets/components/StorageForm.vue
> +      :title="$t('Name')"
so I guess I should fix it for all the uses of FormInput component. am I correct ?

2021-01-09 19:40 UTC, or-yam commented on src/modules/core/components/layout/Header.vue
> +		<span class="user-welcome" v-if="user">{{$t('Hello')}} <strong>{{user.name}}</strong></span>
I'm not sure i understand. can you give an example ? 
Is there more places with this problem ?

2021-01-10 20:44 UTC, davidmeirlevy commented on src/modules/assets/components/StorageForm.vue
> +      :title="$t('Name')"
yes.
revert those changes and only use the $t from inside the FormInput component.

2021-01-10 20:52 UTC, davidmeirlevy commented on src/modules/core/components/layout/Header.vue
> +		<span class="user-welcome" v-if="user">{{$t('Hello')}} <strong>{{user.name}}</strong></span>
look at this one:
https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting
the text inside the translation json can be like `"hello {user}"`.
and then the usage can be: `{{ $t('hello {user}', { user: user.name }) }}`.

it's useful in cases when the translated text is a sentence that can be translated with the opposite order in different languages.
if you need to insert HTML into the translated text (such as `<strong>` element), you can. and then use `v-html="$t('the key')"` as an attribute to the element, instead of the content of the element.

2021-01-19 08:44 UTC, davidmeirlevy requested changes
@or-yam the main issue is to load the language files async.

2021-01-19 08:44 UTC, davidmeirlevy commented on package.json
> +    "vue-i18n": "^8.22.2"
we should move this package to dev dependencies.

2021-01-19 08:44 UTC, davidmeirlevy commented on src/App.vue
> +        i18n.locale = language || 'en'
we should use lazy loading for the languages.
try to use lazy import of webpack, like the example here:
https://kazupon.github.io/vue-i18n/guide/lazy-loading.html

it's important that all language files will be loaded unless it's used.

2021-01-19 08:44 UTC, davidmeirlevy commented on src/i18n/en.json
> +  "welcome user message": "Hello <strong>{userName}</strong>",
the key should be like the actual message: "Hello {userName}"

2021-01-19 08:44 UTC, davidmeirlevy commented on src/i18n/he.json
> +  "welcome user message": "שלום <strong>{userName}</strong>",
update this key accordingly.

2021-01-19 08:44 UTC, davidmeirlevy commented on src/modules/core/components/forms/FormInput.vue
>  			<small v-if="label"> ({{label}})</small>
you can add translation to the label too.

2021-01-19 08:44 UTC, davidmeirlevy commented on src/plugins/i18n.ts
> +import en from '../i18n/en.json'
this should be removed after the languages will be loaded in an async way.

2021-01-23 08:12 UTC, davidmeirlevy commented
@or-yam the build failed..

2021-02-07 09:05 UTC, davidmeirlevy commented
@or-yam  Looks great. Is that also working?

2021-02-07 09:05 UTC, davidmeirlevy approved these changes

2021-02-07 19:44 UTC, or-yam commented
Yes. But I still have some small bugs to fix and some more translations to add.

2021-02-07 20:06 UTC, davidmeirlevy commented
Bugs?

2021-02-08 18:27 UTC, or-yam commented
In the app settings the translations displayed as 'key'. I believe it's something simple to fix.

2021-02-15 16:06 UTC, davidmeirlevy commented
@or-yam I ran this branch locally and it's far from ready..  a lot of bugs.

2021-03-10 10:11 UTC, davidmeirlevy commented
@or-yam  ?

2021-04-27 17:31 UTC, merged